name: Switch Node version
on: 
  pull_request:

jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set var
        run: |
          echo "NODE_VERSION=24" >> $GITHUB_ENV    
      - name: checkout
        uses: actions/checkout@v6
      - name : setup node
        uses: actions/setup-node@v6
        with:
          node-version: '"${{ env.NODE_VERSION }}"'
      -name: check node version
        shell: bash
        run: |
          node -v            
      - name: run test
        shell: bash
        run: |
          npm install
          npm test






