name: interact with Github API
on: 
  pull_request:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
       issues: write
           
    steps:
      - name: create issue
        shell: bash
        run: |
          curl --request POST \
          --url https://api.github.com/repos/agrandmaitre/github_action_template/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ GITHUB_SHA::7 }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ GITHUB_SHA::7 }}_."
            }' \
          --fail
