name: build docker
on: 
  pull_request:
  push:
    branches: 
      - main

jobs:
  run-npm-install:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v6
        - name : setup node
          uses: actions/setup-node@v6
          with:
            node-version: 'lts/*'
        - name: run install
          shell: bash
          run: |
            npm install
            npm test

  docker-file:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    needs: run-npm-install
    steps:
      - name: checkout
        uses: actions/checkout@v6    
      - name: build
        run: |
          docker build -t ${{ github.sha }} .

