name: cache
on: 
  workflow_dispatch:

jobs:
  run-npm-install:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name : setup node
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'

      - name: cache nodes 
        id: cache-node
        uses: actions/cache@v5
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/lockfiles') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: run install
        shell: bash
        run: |
          npm install

  run-npm-test:
    runs-on: ubuntu-latest
    needs: run-npm-install
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: restore cache nodes 
        id: cache-node
        uses: actions/cache/restore@v5
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-

      - name : setup node
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'

      - name: run test
        shell: bash
        run: |
          npm test
