name: npm test matrix
on: 
  workflow_dispatch:

jobs:
  run-npm-install-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
        version: [20, lts]
        include:
          - os: ubuntu-latest
            node: 18
    runs-on: ${{ matrix.os }}
    steps:
        - name: checkout
          uses: actions/checkout@v6
        - name : setup node
          uses: actions/setup-node@v6
          with:
            node-version: ${{ matrix.version }}
        - name: run install
          shell: bash
          run: |
            npm install
            npm test
